const iconMap = {
  '01d': 'wi-day-sunny',
  '01n': 'wi-night-clear',
  '02d': 'wi-day-cloudy',
  '02n': 'wi-night-alt-cloudy',
  '03d': 'wi-cloudy',
  '03n': 'wi-cloudy',
  '04d': 'wi-cloudy-windy',
  '04n': 'wi-cloudy-windy',
  '09d': 'wi-day-rain',
  '09n': 'wi-night-alt-rain',
  '10d': 'wi-day-rain',
  '10n': 'wi-night-alt-rain',
  '11d': 'wi-day-thunderstorm',
  '11n': 'wi-night-alt-thunderstorm',
  '13d': 'wi-day-snow',
  '13n': 'wi-night-alt-snow',
  '50d': 'wi-day-fog',
  '50n': 'wi-night-alt-fog',
};
export default iconMap;